name: GenCore
version: '${project.version}'
main: liltrip.gencore.GenCore
api-version: 1.17
depend:
  - NBTAPI
  - Vault
commands:
  gen:
    aliases:
      - gens
      - generator
      - generators
